export const categories = [
  {
    _id: "1",
    icon: "/icons/dev.svg",
    category: "German Language",
    courses: 45,
  },
  {
    _id: "2",
    icon: "/icons/finance.svg",
    category: "Visa & Immigration",
    courses: 28,
  },
  {
    _id: "3",
    icon: "/icons/network.svg",
    category: "Job Search & Career",
    courses: 32,
  },
  {
    _id: "4",
    icon: "/icons/communication.svg",
    category: "Cultural Integration",
    courses: 25,
  },
  {
    _id: "5",
    icon: "/icons/business.svg",
    category: "Housing & Living",
    courses: 18,
  },
  {
    _id: "6",
    icon: "/icons/science.svg",
    category: "Education in Germany",
    courses: 22,
  },
  {
    _id: "7",
    icon: "/icons/contentwriting.svg",
    category: "Document Preparation",
    courses: 15,
  },
  {
    _id: "8",
    icon: "/icons/marketing.svg",
    category: "Networking & Community",
    courses: 12,
  },
  {
    _id: "9",
    icon: "/icons/art.svg",
    category: "German Culture & Lifestyle",
    courses: 20,
  },
  {
    _id: "10",
    icon: "/icons/photography.svg",
    category: "Travel & Exploration",
    courses: 16,
  },
];

export const courses = [
  {
    _id: "1",
    thumbnail: "/images/img1.png",
    teacher: {
      fullName: "Sarah Schmidt",
      avatar: "https://avatars.githubusercontent.com/u/109316958?s=48&v=4",
    },
    title: "German Language for Beginners (A1-A2)",
    hours: 40,
    students: 850,
    price: 149.99,
    priceOff: 99.99,
    category: "German Language",
    stars: 5,
  },
  {
    _id: "2",
    thumbnail: "/images/img2.png",
    teacher: {
      fullName: "Ahmed Ben Ali",
      avatar: "https://avatars.githubusercontent.com/u/109316958?s=48&v=4",
    },
    title: "How to Apply for a German Work Visa - Complete Guide",
    hours: 15,
    students: 620,
    price: 89.99,
    priceOff: 59.99,
    category: "Visa & Immigration",
    stars: 4.8,
  },
  {
    _id: "3",
    thumbnail: "/images/img3.png",
    teacher: {
      fullName: "Fatma Trabelsi",
      avatar: "https://avatars.githubusercontent.com/u/109316958?s=48&v=4",
    },
    title: "Cultural Adaptation and Life in Germany",
    hours: 25,
    students: 550,
    price: 119.99,
    priceOff: 79.99,
    category: "Cultural Integration",
    stars: 4.9,
  },
  {
    _id: "4",
    thumbnail: "/images/img4.png",
    teacher: {
      fullName: "Mohamed Karim",
      avatar: "https://avatars.githubusercontent.com/u/109316958?s=48&v=4",
    },
    title: "Finding a Job in Germany as a Tunisian Professional",
    hours: 30,
    students: 720,
    price: 139.99,
    priceOff: 89.99,
    category: "Job Search & Career",
    stars: 4.7,
  },
  {
    _id: "5",
    thumbnail: "/images/img5.png",
    teacher: {
      fullName: "Dr. Klaus Weber",
      avatar: "https://avatars.githubusercontent.com/u/109316958?s=48&v=4",
    },
    title: "Understanding German Student Visa Requirements",
    hours: 18,
    students: 480,
    price: 79.99,
    category: "Education in Germany",
    stars: 4.6,
  },
  {
    _id: "6",
    thumbnail: "/images/img6.png",
    teacher: {
      fullName: "Leila Mansouri",
      avatar: "https://avatars.githubusercontent.com/u/109316958?s=48&v=4",
    },
    title: "Finding Affordable Housing in German Cities",
    hours: 20,
    students: 390,
    price: 99.99,
    priceOff: 69.99,
    category: "Housing & Living",
    stars: 4.5,
  },
  {
    _id: "7",
    thumbnail: "/images/img1.png",
    teacher: {
      fullName: "Hans Mueller",
      avatar: "https://avatars.githubusercontent.com/u/109316958?s=48&v=4",
    },
    title: "German Language Intermediate Level (B1-B2)",
    hours: 50,
    students: 670,
    price: 179.99,
    priceOff: 129.99,
    category: "German Language",
    stars: 4.9,
  },
  {
    _id: "8",
    thumbnail: "/images/img2.png",
    teacher: {
      fullName: "Amira Jlassi",
      avatar: "https://avatars.githubusercontent.com/u/109316958?s=48&v=4",
    },
    title: "Writing Perfect German Job Applications (CV & Cover Letter)",
    hours: 12,
    students: 540,
    price: 69.99,
    priceOff: 49.99,
    category: "Document Preparation",
    stars: 4.8,
  },
  {
    _id: "9",
    thumbnail: "/images/img3.png",
    teacher: {
      fullName: "Sami Bouazizi",
      avatar: "https://avatars.githubusercontent.com/u/109316958?s=48&v=4",
    },
    title: "German Healthcare System: A Tunisian's Guide",
    hours: 10,
    students: 310,
    price: 59.99,
    category: "Cultural Integration",
    stars: 4.4,
  },
  {
    _id: "10",
    thumbnail: "/images/img4.png",
    teacher: {
      fullName: "Dr. Anna Fischer",
      avatar: "https://avatars.githubusercontent.com/u/109316958?s=48&v=4",
    },
    title: "German Business Etiquette and Workplace Culture",
    hours: 16,
    students: 450,
    price: 89.99,
    priceOff: 64.99,
    category: "Job Search & Career",
    stars: 4.7,
  },
  {
    _id: "11",
    thumbnail: "/images/img5.png",
    teacher: {
      fullName: "Youssef Slim",
      avatar: "https://avatars.githubusercontent.com/u/109316958?s=48&v=4",
    },
    title: "Family Reunification Visa: Step-by-Step Guide",
    hours: 14,
    students: 280,
    price: 79.99,
    priceOff: 54.99,
    category: "Visa & Immigration",
    stars: 4.6,
  },
  {
    _id: "12",
    thumbnail: "/images/img6.png",
    teacher: {
      fullName: "Nadia Chaieb",
      avatar: "https://avatars.githubusercontent.com/u/109316958?s=48&v=4",
    },
    title: "Navigating German Bureaucracy: Registration & Documents",
    hours: 22,
    students: 520,
    price: 99.99,
    priceOff: 74.99,
    category: "Document Preparation",
    stars: 4.8,
  },
];

export const _categories = [
  {
    _id: "1",
    icon: "/icons/develop.svg",
    title: "German Language",
    description:
      "Master the German language from A1 to C2 levels with comprehensive courses designed for Tunisian learners preparing to study, work, or live in Germany.",
  },
  {
    _id: "2",
    icon: "/icons/finance.svg",
    title: "Visa & Immigration",
    description:
      "Navigate the German visa process with expert guidance on work visas, student visas, family reunification, and permanent residence applications.",
  },
  {
    _id: "3",
    icon: "/icons/business.svg",
    title: "Job Search & Career",
    description:
      "Find your dream job in Germany with courses on job hunting strategies, networking, salary negotiations, and career advancement in the German job market.",
  },
  {
    _id: "4",
    icon: "/icons/communication.svg",
    title: "Cultural Integration",
    description:
      "Adapt to German culture with ease. Learn about social norms, traditions, festivals, and daily life to feel at home in your new country.",
  },
  {
    _id: "5",
    icon: "/icons/design.svg",
    title: "Housing & Living",
    description:
      "Find and secure housing in Germany. Understand rental contracts, apartment hunting tips, and practical advice for settling into German cities.",
  },
  {
    _id: "6",
    icon: "/icons/science.svg",
    title: "Education in Germany",
    description:
      "Everything you need to know about studying in Germany - university applications, student life, scholarships, and academic requirements.",
  },
  {
    _id: "7",
    icon: "/icons/contentwriting.svg",
    title: "Document Preparation",
    description:
      "Create perfect German documents including CVs, cover letters, visa applications, university applications, and official correspondence.",
  },
  {
    _id: "8",
    icon: "/icons/marketing.svg",
    title: "Networking & Community",
    description:
      "Connect with other Tunisians in Germany, build professional networks, and learn strategies for successful integration into German communities.",
  },
];

export const _courses = [
  {
    _id: "1",
    courseImage: "/images/img1.png",
    courseCategory: "German Language",
    courseTitle: "German for Beginners - A1 Level",
    duration: "8 weeks",
    courseDescription: "Start your German language journey with this comprehensive A1 course designed specifically for Tunisian speakers.",
    profileName: "Sarah Schmidt",
    originalPrice: "$149.99",
    discountedPrice: "$99.99",
  },
  {
    _id: "2",

    courseImage: "/images/img2.png",
    courseCategory: "Visa & Immigration",
    courseTitle: "German Work Visa Application Guide",
    duration: "4 weeks",
    courseDescription: "Complete step-by-step guide to applying for and obtaining a German work visa from Tunisia.",
    profileName: "Ahmed Ben Ali",
    originalPrice: "$89.99",
    discountedPrice: "$59.99",
  },
  {
    _id: "3",

    courseImage: "/images/img3.png",
    courseCategory: "Job Search & Career",
    courseTitle: "Landing Your First Job in Germany",
    duration: "6 weeks",
    courseDescription:
      "Practical strategies for finding employment in Germany, from networking to interview preparation.",
    profileName: "Mohamed Karim",
    originalPrice: "$139.99",
    discountedPrice: "$89.99",
  },
  {
    _id: "4",
    courseImage: "/images/img4.png",
    courseCategory: "Cultural Integration",
    courseTitle: "Understanding German Culture and Society",
    duration: "5 weeks",
    courseDescription: "Essential cultural insights to help you integrate smoothly into German society and avoid common cultural misunderstandings.",
    profileName: "Dr. Klaus Weber",
    originalPrice: "$119.99",
    discountedPrice: "$79.99",
  },
  {
    _id: "5",

    courseImage: "/images/img5.png",
    courseCategory: "Housing & Living",
    courseTitle: "Finding Your Home in Germany",
    duration: "3 weeks",
    courseDescription: "Everything you need to know about finding, securing, and moving into an apartment in Germany.",
    profileName: "Leila Mansouri",
    originalPrice: "$99.99",
    discountedPrice: "$69.99",
  },
  {
    _id: "6",

    courseImage: "/images/img6.png",
    courseCategory: "Education in Germany",
    courseTitle: "Applying to German Universities",
    duration: "4 weeks",
    courseDescription:
      "Complete guide to the university application process in Germany, including requirements and best practices.",
    profileName: "Dr. Anna Fischer",
    originalPrice: "$109.99",
    discountedPrice: "$74.99",
  },
  {
    _id: "7",

    courseImage: "/images/img1.png",
    courseCategory: "German Language",
    courseTitle: "German Intermediate - B1 Level",
    duration: "10 weeks",
    courseDescription: "Advance your German language skills to B1 level with intensive conversation practice and grammar.",
    profileName: "Hans Mueller",
    originalPrice: "$179.99",
    discountedPrice: "$129.99",
  },
  {
    _id: "8",

    courseImage: "/images/img2.png",
    courseCategory: "Document Preparation",
    courseTitle: "Perfect German CV and Cover Letter",
    duration: "2 weeks",
    courseDescription:
      "Learn to write compelling German job applications that get you noticed by employers.",
    profileName: "Amira Jlassi",
    originalPrice: "$69.99",
    discountedPrice: "$49.99",
  },
];

export const lessons = [
  {
    _id: "1",
    lessons: 12,
    quizzes: 3,
    category: "German Language",
    title: "German Pronunciation and Basic Grammar",
    author: "Sarah Schmidt",
    courseImage: "",
  },
  {
    _id: "2",
    lessons: 8,
    quizzes: 2,
    category: "Visa & Immigration",
    title: "Understanding German Visa Categories",
    author: "Ahmed Ben Ali",
    courseImage: "",
  },
  {
    _id: "3",
    lessons: 15,
    quizzes: 4,
    category: "Job Search & Career",
    title: "Navigating the German Job Market",
    author: "Mohamed Karim",
    courseImage: "",
  },
  {
    _id: "4",
    lessons: 10,
    quizzes: 2,
    category: "Cultural Integration",
    title: "German Social Norms and Etiquette",
    author: "Dr. Klaus Weber",
    courseImage: "",
  },
  {
    _id: "5",
    lessons: 7,
    quizzes: 1,
    category: "Housing & Living",
    title: "Apartment Hunting in Major German Cities",
    author: "Leila Mansouri",
    courseImage: "",
  },
  {
    _id: "6",
    lessons: 9,
    quizzes: 2,
    category: "Education in Germany",
    title: "German University Application Process",
    author: "Dr. Anna Fischer",
    courseImage: "",
  },
  {
    _id: "7",
    lessons: 14,
    quizzes: 3,
    category: "Document Preparation",
    title: "Writing Professional German Documents",
    author: "Amira Jlassi",
    courseImage: "",
  },
  {
    _id: "8",
    lessons: 6,
    quizzes: 1,
    category: "Networking & Community",
    title: "Building Your Network in Germany",
    author: "Sami Bouazizi",
    courseImage: "",
  },
  {
    _id: "9",
    lessons: 11,
    quizzes: 2,
    category: "German Language",
    title: "Conversational German for Daily Life",
    author: "Hans Mueller",
    courseImage: "",
  },
  {
    _id: "10",
    lessons: 8,
    quizzes: 2,
    category: "Job Search & Career",
    title: "German Interview Preparation",
    author: "Nadia Chaieb",
    courseImage: "",
  },
  {
    _id: "11",
    lessons: 13,
    quizzes: 3,
    category: "Cultural Integration",
    title: "Understanding German Healthcare System",
    author: "Fatma Trabelsi",
    courseImage: "",
  },
  {
    _id: "12",
    lessons: 9,
    quizzes: 2,
    category: "Visa & Immigration",
    title: "Family Reunification in Germany",
    author: "Youssef Slim",
    courseImage: "",
  },
  {
    _id: "13",
    lessons: 12,
    quizzes: 3,
    category: "German Language",
    title: "Business German for Professionals",
    author: "Sarah Schmidt",
    courseImage: "",
  },
  {
    _id: "14",
    lessons: 8,
    quizzes: 2,
    category: "Housing & Living",
    title: "German Rental Contracts and Rights",
    author: "Ahmed Ben Ali",
    courseImage: "",
  },
  {
    _id: "15",
    lessons: 10,
    quizzes: 2,
    category: "Education in Germany",
    title: "Scholarships and Funding for International Students",
    author: "Mohamed Karim",
    courseImage: "",
  },
  {
    _id: "16",
    lessons: 7,
    quizzes: 1,
    category: "Networking & Community",
    title: "Tunisian Community in Germany",
    author: "Dr. Klaus Weber",
    courseImage: "",
  },
];

export const badges = [
  { name: "All" },
  { name: "German Language" },
  { name: "Visa & Immigration" },
  { name: "Job Search" },
  { name: "Cultural Integration" },
  { name: "Housing" },
];
